name: Magiccast
version: '${version}'
main: distortiongate.magiccast.Magiccast
api-version: 1.18
authors: [ sota70 ]
description: This plugins produces awesome magic casting system
commands:
  sethologrampattern:
    description: It sets hologram spawn pattern each players have
    usage: "Usage: /[sethologrampattern | sethp] [player name] [hologram pattern]"
    aliases: sethp
